# Generated by Django 4.1.7 on 2023-07-16 05:51

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(default=data.models.generate_coupon_code, max_length=500, unique=True)),
                ('expirationDate', models.DateField()),
                ('discountAmount', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
