# Generated by Django 4.1.7 on 2023-07-16 02:28

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='couponCode',
            field=models.CharField(default=data.models.generate_coupon_code, max_length=500, unique=True),
        ),
    ]
